version: "3.9"
services:
  flutter:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - flutter_cache:/root/.pub-cache
    env_file:
      - .env
    command: flutter run -d web-server --web-port=8080 --web-hostname=0.0.0.0

volumes:
  flutter_cache:
